# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fportalo <fportalo@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/11/13 12:22:57 by fportalo          #+#    #+#              #
#    Updated: 2020/11/13 12:28:12 by fportalo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = -gcc

FLAGS = -Werror -Wextra -Wall

PARSE = main.c parse_test.c gnl/get_next_line_bonus.c gnl/get_next_line_utils_bonus.c

parse:
	@$(CC) $(FLAGS) $(PARSE)
